version: "3.2"
services:
  frontend:
    build: ./
    volumes:
      - $PWD:/app
      # One-way volume to use node_modules from inside image
      - /node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    
    
